### PR TITLE
Ignore ghost jids that have no real job

### PR DESCRIPTION
**Pull request by tdg5**
Sometimes a jid gets stuck in the system even though the job it's associated with has been deleted. This change makes it so that jids with no associated job will be reaped via the queue pop process. Any jid without a job is dropped on the floor and ignored.

### CODE REVIEW

**Comment by mhoydis** [comment]
Is it worth logging something in the case it reaps a jid in this fashtion?

**Comment by mwooddatto** [comment]
LGTM

**Comment by tdg5** [comment]
@mhoydis there's not an easy way to log since this is all happening inside the redis server. The only reason we get other messages sometimes is because the action fails and the failure is logged by the worker. I could see value in logging something, but there's not really a way to do it without bubbling the error to the client.

**Comment by mhoydis** [comment]
okie dokie 🍔

**Comment by cmatysik** [comment]
I don't know Lua, but what you did makes sense (it looks similar to any other scripting language)

LGTM

**Pull request merged**
